import { texturaDeMapa, conferirMapa } from './pixel.js';

// ARQUIVO GERADO por ferramentas/gerar.py — edite o pintor, nao este arquivo.
// Retratos de busto 64x64 para a caixa de dialogo.

const LEGENDA = {
  o: '#2a1a16',
  s: '#e8b98c', S: '#c9946a', h: '#f7d9b4', B: '#e8a08c',
  K: '#3d2517', L: '#5c3a22',
  G: '#5a5560', g: '#8a8694',
  w: '#f7f0e2', W: '#ffffff', I: '#5c3a22', R: '#a8624a',
  c: '#cc6a35', C: '#9c3f26', b: '#ef9a5c',
  N: '#26304a', n: '#39466b', T: '#a83a32',
  d: '#33456a', D: '#1e2b43',
  t: '#241c22', u: '#4a3d4e',
  r: '#d94f45', p: '#ef7a5a', q: '#b03a34',
  A: '#1c1a22', a: '#3a3644', v: '#2f6b3a', V: '#1f4a28', J: '#3a3a44', M: '#4a4a58',
  Q: '#c4b498', Y: '#e0a05c', y: '#b07a3c',
  Z: '#241812', E: '#3d2a24', X: '#b8907a', U: '#2f5a9a', z: '#c8a24a', P: '#c07068',
  e: '#efcdb0', f: '#d4a888', x: '#101014',
};

const RETRATO_PEDRO = [
  '.........................oooooZZZZZZZZZZZZZZZZZoo...............',
  '......................oooZZZZZZZZZZZEEEEZZZZZZZZZo..............',
  '..................ooooZZZZZZZEEEEEZZEEEEZZZZZZZZZZo.............',
  '.................oZZZZZZZZZZZEEEEEZZZZZZZZZZZZZZZZZo............',
  '...............ooZZZZZZZZZZZZZZZZZZZZZZZZZZEEEZZZZZo............',
  '..............oZZZZZZZEEEEZZZZZZZZZZZZZZZZZEEEZZZZZo............',
  '.............oZZZZZZZZEEEEZZZZZZZZZZZZZZZZZZZZZZZZZZo...........',
  '.............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '.............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '.............oZZZZEEEZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '.............oZZZZEEEZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo...........',
  '.............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo............',
  '.............oZZZZZZssZZZZZZZZZZZZZZZZZZZZZZssZZZZo.............',
  '.............oZZZZZZsssZZZZZZZZZZZZZZZZZZZZZssZZZZo.............',
  '.............oZZZZsssshhhhhhhhhsZsssssssssssssZZZZo.............',
  '.............oZZZZssssshhhhhhhssssssssssssssssZZZZo.............',
  '.............oZZZZsssZZZZZZhhsssssssZZZZZZssssZZZZo.............',
  '.............oZZZZsssZZZZZZZsssssssZZZZZZZssssZZZZo.............',
  '.............oZZZZsssssssssZsssssssZssssssssssZZZZo.............',
  '.............oZZZZssssssssssssssssssssssssssssssSSSo............',
  '............osssssssssoooooossssssssoooooosssssSSSSSo...........',
  '............ossssssssowwWZZwossssssowwWZZwossssSSSSSo...........',
  '............ossSsssssswwZoZwsssssssswwZoZwsssssSSoSSo...........',
  '............ossssssssswwZoZwsssssSsswwZoZwsssssSSSSSo...........',
  '............ossssssssswwZZZwsssssSsswwZZZwsssssSSSSSo...........',
  '.............ossssssssshhhhhsssssSssssssssssssSSSSSo............',
  '..............osossssshhhhhhhssssSssssssssssssSSoSo.............',
  '...............oosssBBshhhhhsssssSsssssssssBBsSSoo..............',
  '.................ossssssshssssSssSsssssssssssSSo................',
  '.................osssssssssssXsSSXSosXsssssssSSo................',
  '..................osssssssosssssssssssossssssSo.................',
  '..................ossssssssooooooooooossssssSSo.................',
  '..................ossssssssWWWWWWWWWWWssssssSSo.................',
  '...................osssssssswQwwQwwQwsssssssSo..................',
  '....................osssssssRRRRRRRRRssssssso...................',
  '....................ossssssssSSSSSSSsssssssSo...................',
  '.....................oXSSSXSSSXSSSXSSSXSSSXo....................',
  '......................ooSXSSSXSSSXSSSXSSSoo.....................',
  '........................ooSSXSSSXSSSXSSoo.......................',
  '.........................oSXSSSXSSSXSSo.........................',
  '.........................ossssSSSSSSSSo.........................',
  '........................oossssSSSSSSSSooo.......................',
  '.....................oooaassssSSSSSSSSaaaooo....................',
  '................oooooaaaSSSSSSSSSSSSSSSSSaaaooooo...............',
  '............ooooAAAAaaSSSSSSSSSSSSSSSSSSSSSaaAAAAoooo...........',
  '..........ooAAAAAAAaaSSSSSSSSSSSSSSSSSSSSSSSaaAAAAAAAoo.........',
  '.......oooAAAAAAAAaaaaSSSSSSSSSSSSSSSSSSSSSaaaaAAAAAAAAooo......',
  '.....ooAAAAAAAAAAAAaaaaaSSSSSSSSSSSSSSSSSaaaaaAAAAAAAAAAAAoo....',
  '....oAAAAAAAAAAAAAAAaaaaaaaaaaaaSaaaaaaaaaaaaAAAAAAAAAAAAAAAo...',
  '..ooAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAoo.',
  '.oAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAo',
  'oAAAAAAAAxxxxxxAAAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAxxxxxxAAAAAAAAA',
  'AAAAAAAAAxxxxxxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxxxxxxAAAAAAAAA',
  'AAAAAAAAAxxxxxxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxxxxxxAAAAAAAAA',
];

const RETRATO_VICTOR = [
  '................................................................',
  '................................................................',
  '................................................................',
  '................................................................',
  '................................o...............................',
  '........................ooooooooZoooooooo.......................',
  '.....................oooZZZZZZZZZZZZZZZZZooo....................',
  '...................ooZZZZZZZZZZZZZZZZZZZZZZZoo..................',
  '..................oZZZZZZZZZZZZZZZZZZZZZZZZZZZo.................',
  '.................oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo................',
  '................oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo...............',
  '................oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo...............',
  '...............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo..............',
  '...............oZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZo...............',
  '...............oZZZZZeZZZZZZZZZZZZZZZZZZZZZeZZZZo...............',
  '...............oZZeeeeeeeZZZZZZZZZZZZZZZeeeeeeeZo...............',
  '...............oeeeeeeeeeeeZZZZZZZZZZZeeeeeeeeeeeo..............',
  '..............oZeeeeeeeeeeZZZZZZZZZZZZZeeeeeeeeeeo..............',
  '..............oeeeeeeeeeeeeeZZZZZZZZZeeeeeeeeeeeeeo.............',
  '..............oZeeeeeeeeeeeeeeeeZeeeeeeeeeeeeeeeeo..............',
  '..............oZeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeo..............',
  '..............oZZZeeeeeeeeheeeeeeeeeeeeeeeeeeeeZZo..............',
  '..............oZZZZeeeeehhhhheeeeeeeeeeeeeeeeZZZZo..............',
  '..............oZZZZeeeehhhhhhheeeeeeeeeeeeeeeZZZZo..............',
  '..............oZZZZeeehhhhhhhfffffffeeeeeeeeeZZZZo..............',
  '..............oZZZZeeeZZZZZZhheeeeeZZZZZZeeeeZZZZo..............',
  '...............ooeeeeZZZZZZZheeeeeeZZZZZZZeeeeeeo...............',
  '...............ooeeeeZeeeeheeeeeeeeeeeeeeZeeeeeeoo..............',
  '..............oeoeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeofo.............',
  '.............oeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffo............',
  '............oeeeeeeeeeooooooeeeeeeeeooooooeeeeefffffo...........',
  '............oeeeeeeeeowwWKKwoeeeeeeowwWKKwoeeeefffffo...........',
  '............oeefeeeeeewwKoKweeeeeeeewwKoKweeeeeffoffo...........',
  '............oeeeeeeeeewwKoKweeeeefeewwKoKweeeeefffffo...........',
  '............oeeeeeeeeewwKKKweeeeefeewwKKKweeeeefffffo...........',
  '.............oeeeeeeeeehhhhheeeeefeeeeeeeeeeeefffffo............',
  '..............oeoeeefffffhhhheeeefeeeeeefffffeffofo.............',
  '...............o.oeeeeehhhhheeeeefeeeeeeeeeeeefo.o..............',
  '.................oeeeeeeeheeeefeefeeeeeeeeeeeffo................',
  '..................oeeeeeeeeeeeeffffoeeeeeeeeefo.................',
  '..................oeeeeeeeeZZgZZZZZgZZeeeeeeefo.................',
  '..................oeeeeeeeZeeeeeeeeeeeZeeeeeffo.................',
  '...................oeeeeeeeeeeeeeeeeeeeeeeeefo..................',
  '...................oeeeeeeeeeRRRRRRReeeeeeeefo..................',
  '....................oeeeeeeeefffffffeeeeeeeeo...................',
  '.....................oeeeeegZZZZZZgZZZeeeeeo....................',
  '.....................offfffZZgZZZZZZgZfffffo....................',
  '......................ooffffZZZgZZZZZffffoo.....................',
  '........................offfZZZZZgZZZfffo.......................',
  '.......................ooofffZZZZZZgffoooo......................',
  '.....................oowwweeeeffefffffwwwwoo....................',
  '................oooooaAwwwewwwwwwwwwwwwwwwAaooooo...............',
  '............ooooAAAAAaAAwwwwwwwwwwwwwwwwwAAaAAAAAoooo...........',
  '..........ooAAAAAAAAAAaAwweeeeffffffffwwwAaAAAAAAAAAAoo.........',
  '.......oooAAAAAAAAAAAAaAAwwwwUUUUUUwwwwwAAaAAAAAAAAAAAAooo......',
  '.....ooAAAAAAAAAAAAAAAaAAwwwwUUUUUUwwwwwAAaAAAAAAAAAAAAAAAoo....',
  '...ooAAAAAAAAAAAAAAAAAAaAAwwwwUUUUwwwwwAAaAAAAAAAAAAAAAAAAAAoo..',
  '..oAAAAAAAAAAAAAAAAAAAAaAAwwwwUUUUwwwwwAAaAAAAAAAAAAAAAAAAAAAAo.',
  'ooAAAAAAAAAAAAAAAAAAAAAaAAAwwwUWUUwwwwAAAaAAAAAAAAAAAAAAAAAAAAAo',
  'AAAAAAAAAAAAAAAAAAAAAAAAaAAwwwUUUUwwwwAAaAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAaAAAwwUUUUwwwAAAaAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAaAAAwwUUWUwwwAAAaAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAaAAAwUUUUwwAAAaAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAaAAAwWUUUwwAAAaAAAAAAAAAAAAAAAAAAAAAAAA',
];

const RETRATO_SABRINA = [
  '................................o...............................',
  '.........................oooooooKooooooo........................',
  '......................oooKKKKKKKKKKKKKKKooo.....................',
  '....................ooKKKKKKKKKKKKKKKKKKKKKoo...................',
  '..................ooKKKKKKKKKKKKKKKKKKKKKKKKKoo.................',
  '.................oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo................',
  '................oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...............',
  '...............oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..............',
  '..............oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo.............',
  '.............oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo............',
  '............oKKKKKKKKKKKLLLLLLLLLLLKKKKKKKKKKKKKKKKKo...........',
  '............oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...........',
  '...........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '...........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '...........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '...........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '..........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo.........',
  '..........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '..........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '..........oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..........',
  '..........oKKKKKKKKsKKKKKKKKKKKKKKKKKKKKKKKKsKKKKKKKKo..........',
  '..........oKKKKKKKKssssKKKKKKKKKKKKKKKKKKssssKKKKKKKKo..........',
  '..........oKKKKKKKKssssshhKKKKKKKKKKKKsssssssKKKKKKKKo..........',
  '..........oKKKKKKKKsssshhhhhhKKKKKKKKKKKKssssKKKKKKKKo..........',
  '..........oKKKKKKKKssshhhhhhhhhsKKKKKKKKKKKKsKKKLKKKKo..........',
  '..........oKKKKKKKKsssshhhhhhhsssssKKKKKKKKKKKKKLKKKKo..........',
  '..........oKKKKKKLKssZZZZZZZhssssssZZZKKKKKKKKKKLKKKKo..........',
  '..........oKKKKKKLKssZZZZZZZsssssssZZZZZZKKKKKKKLKKKKo..........',
  '..........oKKKKKKLKssssssssssssssssssssssssssKKKLKKKKo..........',
  '..........oKKKKKKLKssssssssssssssssssssssssssKKKLKKKKo..........',
  '..........oKKKKKKLKssooooooossssssssooooooossKKKLKKKKo..........',
  '..........oKKKKKKLKsoowwWKKwossssssowwWKKwoosKKKLKKKKo..........',
  '..........oKKKKKKLKssswwKoKwsssssssswwKoKwsssKKKLKKKKo..........',
  '..........oKKKKKKLKssswwKoKwsssssSsswwKoKwsssKKKLKKKKo..........',
  '..........oKKKKKKLKzsswwKKKwsssssSsswwKKKwssszKKKLKKKo..........',
  '..........oKKKKKLKKsssshhhhhsssssSsssssssssssKKKKLKKKo..........',
  '..........oKKKKKLKKssshhhhhhhssssSsssssssssssKKKKLKKKo..........',
  '..........oKKKKKLKKsBBshhhhhsssssSsssssssssBBKKKKLKKKo..........',
  '..........oKKKKKLKKsssssshssssSssSsssssssssssKKKKLKKKo..........',
  '..........oKKKKKLKKssssssssssssSSSSosssssssssKKKKLKKKo..........',
  '..........oKKKKKLKKssssssssssssssssssssssssssKKKKLKKKo..........',
  '..........oKKKKKLKKKssssssssPssssssssPssssssSKKKKLKKKo..........',
  '..........oKKKKKLKKKsssssssssPPPPPPPPsssssssSKKKKLKKKo..........',
  '..........oKKKKKLKKKKsssssssssPPPPPSssssssssKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKsssssssssssssssssssssKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKsssssssssssssssssssssKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKSSSSSSSSSSSSSSSSSKKKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKKSSSSSSSSSSSSSSSKKKKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKKKSSSSSSSSSSSSKKKKKKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKKKSSSSSSSSSSSSKKKKKKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKKKsswQwQwQwQwSKKKKKKKKKKKLKKKo..........',
  '..........oKKKKKLKKKKKKKKQwQssSSSSSSSQwQKKKKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKKKKwKssssSSSSSSSSKKwKKKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKKKQKAssssSSSSSSSSKAKQKKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKKwKKAKKKKKKKKKKKKKAKKwKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKKKKAKKKKKKKzKKKKKKKAKKKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKKKKAKKKKKKzszKKKKKKAKKKKKKKKKLKKo..........',
  '..........oKKKKLKKKKKsssAssssszszszsssssAsssKKKKKKLKKo..........',
  '..........oKKKKLKKKsssssAsssssssssssssssAssssKKKKKLKKo..........',
  '..........oKKKKLKKKssssAsssssssssssssssssAsssKKKKKLKKoo.........',
  '........oossKKKLKKKssssAssssssssAssssssssAsssKKKKKLKKssoo.......',
  'oooooooossssKKKKKKKssrrAssAvvAAAAYYAAAAvvAsssKKKKKKKKssssooooooo',
  'ssssssssssssKKKKKKKssrrAYYAvvAUUAYYArrAvvAAssKKKKKKKKsssssssssss',
  'ssssssssssssKKKKKKKssAAAYYAAAAUUAAAArrAAAAAAsKKKKKKKKsssssssssss',
];

export function carregarRetratos(cena) {
  texturaDeMapa(cena, 'retratoPedro', conferirMapa('retratoPedro', RETRATO_PEDRO), LEGENDA);
  texturaDeMapa(cena, 'retratoVictor', conferirMapa('retratoVictor', RETRATO_VICTOR), LEGENDA);
  texturaDeMapa(cena, 'retratoSabrina', conferirMapa('retratoSabrina', RETRATO_SABRINA), LEGENDA);
}

export const RETRATOS = { pedro: 'retratoPedro', victor: 'retratoVictor' };
